// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantFlowBots.Infrastructure.Persistence;

#nullable disable

namespace QuantFlowBots.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuantFlowBotsDbContext))]
    partial class QuantFlowBotsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("qfb")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyPreview")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("UserId", "ExchangeId", "Label")
                        .IsUnique();

                    b.HasIndex("UserId", "ExchangeId", "Mode", "IsActive");

                    b.ToTable("api_keys", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Backtest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("backtests", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AtrMultiplier")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("AtrPeriod")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseEquityUsdt")
                        .HasColumnType("numeric(28,12)");

                    b.Property<bool>("BreakEvenEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BreakEvenOffsetPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("BreakEvenTriggerPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("CooldownAfterLossMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyLossStopPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("DefaultStopLossPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("DefaultTakeProfitPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("DefaultTrailingStopPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<bool>("KillSwitchEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KillSwitchReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("KillSwitchTrippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("KindConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("Leverage")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConsecutiveLosses")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOpenPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxPositionSize")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("RiskPerTradePercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("RunMode")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("StopLossKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SymbolFilterJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<string>("TakeProfitLevelsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("UserId", "State");

                    b.ToTable("bots", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.BotRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("RealizedPnl")
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StopReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "StartedAt");

                    b.ToTable("bot_runs", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Candle", b =>
                {
                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(28,12)");

                    b.HasKey("SymbolId", "Interval", "OpenTime");

                    b.HasIndex("SymbolId", "Interval", "OpenTime")
                        .IsDescending(false, false, true);

                    b.ToTable("candles", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RestBaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WebSocketBaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("exchanges", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric(28,12)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(28,12)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotRunId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.HasIndex("BotId", "CreatedAt");

                    b.ToTable("orders", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BreakEvenTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric(28,12)");

                    b.Property<string>("ExchangePositionRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExchangeStopOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExchangeTpOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal?>("HighestPriceSinceEntry")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("RealizedPnl")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLossPrice")
                        .HasColumnType("numeric(28,12)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<string>("TakeProfitLevelsJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal?>("TrailingStopPercent")
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("BotRunId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("BotId", "Status");

                    b.ToTable("positions", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.RiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("risk_events", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.SentimentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Magnitude")
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SymbolCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("IngestedAt");

                    b.HasIndex("SymbolId");

                    b.HasIndex("SymbolCode", "At");

                    b.ToTable("sentiment_events", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(10,4)");

                    b.Property<int?>("Side")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.HasIndex("StrategyId", "GeneratedAt");

                    b.ToTable("signals", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("strategies", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FiltersUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ListedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinNotional")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric(28,12)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("StepSize")
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric(28,12)");

                    b.HasKey("Id");

                    b.HasIndex("ListedAt");

                    b.HasIndex("ExchangeId", "Code")
                        .IsUnique();

                    b.ToTable("symbols", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.SymbolRiskFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("symbol_risk_flags", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "qfb");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("TelegramAlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TelegramBotToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WallAlertBotToken")
                        .HasColumnType("text");

                    b.Property<string>("WallAlertChatId")
                        .HasColumnType("text");

                    b.Property<int>("WallAlertCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("WallAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WallAlertMaxDistancePct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WallAlertMinNotional")
                        .HasColumnType("numeric");

                    b.Property<string>("WallAlertSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhaleAlertBotToken")
                        .HasColumnType("text");

                    b.Property<string>("WhaleAlertChatId")
                        .HasColumnType("text");

                    b.Property<int>("WhaleAlertCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("WhaleAlertDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WhaleAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("WhaleAlertIntervals")
                        .HasColumnType("text");

                    b.Property<int>("WhaleAlertLookback")
                        .HasColumnType("integer");

                    b.Property<decimal>("WhaleAlertMinVolume24h")
                        .HasColumnType("numeric");

                    b.Property<string>("WhaleAlertMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WhaleAlertMultiplier")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", "qfb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Backtest", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("Symbol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Bot", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuantFlowBots.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.User", "User")
                        .WithMany("Bots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("Strategy");

                    b.Navigation("Symbol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.BotRun", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Candle", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Order", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.BotRun", "BotRun")
                        .WithMany()
                        .HasForeignKey("BotRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("BotRun");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Position", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.BotRun", "BotRun")
                        .WithMany()
                        .HasForeignKey("BotRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("BotRun");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.RiskEvent", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.SentimentEvent", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Signal", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuantFlowBots.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.User", "User")
                        .WithMany("Strategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Symbol", b =>
                {
                    b.HasOne("QuantFlowBots.Domain.Entities.Exchange", "Exchange")
                        .WithMany("Symbols")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("QuantFlowBots.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Bots");

                    b.Navigation("Strategies");
                });
#pragma warning restore 612, 618
        }
    }
}
